packages:
  - "apps/*"
  - "packages/*"
  - "functions"

allowBuilds:
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false

onlyBuiltDependencies:
  - "@firebase/util"
  - "protobufjs"
  - "@next/swc-darwin-arm64"
  - "esbuild"
